---
title: Designer
email: your-email@domain.com
url: https://heydavid-dev.github.io
baseurl: "/freelancer-clone-1-270"
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
keywords: your keywords, separated by commas
skills: Happiness
meta-author: LastName FirstName
google-verify: ''
bing-verify: ''
disqus-shortname: myshortname
color:
  primary: fffb00
  secondary: 00f900
  secondary-dark: '942192'
about:
  title: About
  first-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
    at augue sollicitudin, facilisis purus eu, facilisis quam. Aenean in libero ut
    leo maximus pellentesque ac non lectus. Nunc et sapien lacus. Class aptent taciti
    sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce
    sapien nulla, auctor ac nunc ac, interdum aliquet enim. Suspendisse viverra cursus
    nulla id dignissim. Morbi et tristique orci. Mauris id cursus tortor. Donec volutpat
    ut orci non rutrum. Phasellus rhoncus, libero vel molestie blandit, dolor mi ornare
    ipsum, id bibendum tellus metus ac ex. Vivamus ac nibh finibus, mattis nisl eget,
    tempus ex. Sed sit amet finibus nunc, at maximus augue. Fusce ut placerat tellus.
    Aliquam a ante scelerisque, rutrum libero sit amet, rutrum dui. Donec blandit
    ante et nisl imperdiet, sed congue justo sodales. Aliquam tempor sagittis tempor.
  second-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla
    at augue sollicitudin, facilisis purus eu, facilisis quam. Aenean in libero ut
    leo maximus pellentesque ac non lectus. Nunc et sapien lacus. Class aptent taciti
    sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce
    sapien nulla, auctor ac nunc ac, interdum aliquet enim. Suspendisse viverra cursus
    nulla id dignissim. Morbi et tristique orci. Mauris id cursus tortor. Donec volutpat
    ut orci non rutrum. Phasellus rhoncus, libero vel molestie blandit, dolor mi ornare
    ipsum, id bibendum tellus metus ac ex. Vivamus ac nibh finibus, mattis nisl eget,
    tempus ex. Sed sit amet finibus nunc, at maximus augue. Fusce ut placerat tellus.
    Aliquam a ante scelerisque, rutrum libero sit amet, rutrum dui. Donec blandit
    ante et nisl imperdiet, sed congue justo sodales. Aliquam tempor sagittis tempor.
  button-url: https://github.com/jeromelachaud/freelancer-theme
  button-text: Download Theme
contact:
  title: Contact Me
portfolio:
  title: Portfolio
footer:
  location: Address
  credits: Built By
social-list:
- title: search
  url: mailto:someone@example.com
- title: search
  url: tel:123-456-7890
- title: search
  url: https://wa.me/1234567890
- title: search
  url: https://goo.gl/maps/cb49MvbmdRehc7Zf9
- title: search
  url: https://twitter.com
address: '123'
credits: Freelancer is a free to use, open source theme, created by Start Bootstrap.
markdown: kramdown
permalink: pretty
